'use client';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
type Message = { id:string; role:'user'|'assistant'; text:string; at:string; status?:'sending'|'sent'|'error' };
const STORAGE = 'instinct-mail-chat-v1';
function uid() { return crypto.randomUUID(); }
function time(at:string) { return new Intl.DateTimeFormat('he-IL',{hour:'2-digit',minute:'2-digit'}).format(new Date(at)); }
export default function Chat() {
  const [chatId,setChatId]=useState(''); const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(''); const [ready,setReady]=useState(false); const [online,setOnline]=useState(true); const bottom=useRef<HTMLDivElement>(null);
  useEffect(()=>{ const saved=localStorage.getItem(STORAGE); if(saved){try{const v=JSON.parse(saved); setChatId(v.chatId||uid()); setMessages(v.messages||[]);}catch{setChatId(uid());}} else setChatId(uid()); setReady(true); },[]);
  useEffect(()=>{ if(ready&&chatId)localStorage.setItem(STORAGE,JSON.stringify({chatId,messages})); bottom.current?.scrollIntoView({behavior:'smooth'}); },[messages,chatId,ready]);
  useEffect(()=>{ if(!chatId)return; let live=true; const poll=async()=>{try{const r=await fetch(`/api/messages?chatId=${encodeURIComponent(chatId)}`,{cache:'no-store'}); if(!r.ok)throw 0; const data=await r.json(); if(!live)return; setOnline(true); setMessages(prev=>{const known=new Set(prev.map(m=>m.id)); const fresh=(data.messages||[]).filter((m:Message)=>!known.has(m.id)); return fresh.length?[...prev,...fresh].sort((a,b)=>a.at.localeCompare(b.at)):prev;});}catch{if(live)setOnline(false);}}; poll(); const i=setInterval(poll,6000); return()=>{live=false;clearInterval(i)};},[chatId]);
  const waiting=useMemo(()=>messages.length>0&&messages[messages.length-1].role==='user'&&messages[messages.length-1].status!=='error',[messages]);
  async function send(e:FormEvent){e.preventDefault();const body=text.trim();if(!body||!chatId)return;const msg:Message={id:uid(),role:'user',text:body,at:new Date().toISOString(),status:'sending'};setMessages(p=>[...p,msg]);setText('');try{const r=await fetch('/api/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chatId,text:body,messageId:msg.id})});if(!r.ok)throw 0;setMessages(p=>p.map(m=>m.id===msg.id?{...m,status:'sent'}:m));}catch{setMessages(p=>p.map(m=>m.id===msg.id?{...m,status:'error'}:m));}}
  function reset(){if(confirm('למחוק את השיחה מהמכשיר הזה?')){setMessages([]);setChatId(uid());}}
  if(!ready)return null;
  return <main className="shell"><header><div className="avatar">I</div><div><h1>Instinct</h1><p><span className={online?'dot':'dot off'}/>{online?'מחובר':'מתחבר מחדש...'}</p></div><button onClick={reset} className="clear" aria-label="מחיקת שיחה">⋮</button></header><section className="messages" aria-live="polite">{messages.length===0&&<div className="welcome"><div className="spark">✦</div><h2>היי יוני</h2><p>אפשר לכתוב לי כאן בדיוק כמו בוואטסאפ.</p><div className="note">ההודעות עוברות אליי במייל, והתשובה מופיעה כאן אוטומטית.</div></div>}{messages.map(m=><div key={m.id} className={`row ${m.role}`}><div className="bubble"><div>{m.text}</div><small>{time(m.at)} {m.role==='user'&&(m.status==='sending'?'◷':m.status==='error'?'!':'✓')}</small></div>{m.status==='error'&&<button className="retry" onClick={()=>{setText(m.text);setMessages(p=>p.filter(x=>x.id!==m.id));}}>נסה שוב</button>}</div>)}{waiting&&<div className="typing"><i/><i/><i/></div>}<div ref={bottom}/></section><form onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} placeholder="הודעה ל-Instinct" rows={1}/><button disabled={!text.trim()} aria-label="שליחה">➤</button></form></main>;
}
